name: Build

on:
  push:

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: LibraryMerger.xcodeproj
          scheme: LibraryMerger
          destination: platform=iOS Simulator,name=iPhone 17 Pro
          action: build
